#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: circleci/openjdk:11.0-jdk

only-main: &only-main
  filters:
    branches:
      only:
        - main
        - mvn-central-release

commands:
  install_sdk:
    description: "Install the DAML SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            ./scripts/install-daml.sh << parameters.version >>

jobs:
  blackduck_check:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-{{ checksum ".circleci/config.yml" }}
            - m2
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Maven Build
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            mvn clean package
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_daml_maven_plugin main --logging.level.com.synopsys.integration=DEBUG --detect.notices.report=true --detect.report.timeout=480
      - run:
          command: cp digitalasset_daml_maven_plugin_main_Black_Duck_Notices_Report.txt NOTICE
      - persist_to_workspace:
          root: .
          paths:
            - "NOTICE"

  mvn_test:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-{{ checksum ".circleci/config.yml" }}
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            mvn verify
      - save_cache:
          paths:
            - ~/.m2
            - ~/.daml
          key: m2-{{ checksum "pom.xml" }}-{{ checksum ".circleci/config.yml" }}
  mvn_publish:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - run:
          command: |
            if git log -m -1 --name-only | grep VERSION; then
              echo "Version file changed. Creating a release."
              bash -x ./scripts/release.sh "${MAVEN_USERNAME}" "${MAVEN_PASSWORD}" "${GPG_SIGNING_KEY}" "${GPG_PASSPHRASE}" << parameters.daml_sdk_version >>
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - blackduck_check:
          daml_sdk_version: "2.7.1"
          context: blackduck
      - mvn_test:
          daml_sdk_version: "2.7.1"
          context: blackduck
  build_and_release:
    jobs:
      - mvn_publish:
          <<: *only-main
          daml_sdk_version: "2.7.1"
          context: github-refapp-repo-context
